// <auto-generated />
using System;
using C43_G03_Ef03.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C43_G03_Ef03.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    partial class CompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C43_G03_Ef03.models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deptname");

                    b.Property<int>("ManageId")
                        .HasColumnType("int");

                    b.HasKey("DeptId");

                    b.HasIndex("ManageId")
                        .IsUnique();

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("C43_G03_Ef03.models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("EmpAge");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpolyeeDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EmpSalary");

                    b.HasKey("EmpId");

                    b.HasIndex("EmpolyeeDepartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("C43_G03_Ef03.models.Department", b =>
                {
                    b.HasOne("C43_G03_Ef03.models.Employee", "Manager")
                        .WithOne("ManageDept")
                        .HasForeignKey("C43_G03_Ef03.models.Department", "ManageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("C43_G03_Ef03.models.Employee", b =>
                {
                    b.HasOne("C43_G03_Ef03.models.Department", "empolyeedepartment")
                        .WithMany("Employees")
                        .HasForeignKey("EmpolyeeDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("C43_G03_Ef03.models.Address", "EmpAddress", b1 =>
                        {
                            b1.Property<int>("EmployeeEmpId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeEmpId");

                            b1.ToTable("Employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeEmpId");
                        });

                    b.Navigation("EmpAddress");

                    b.Navigation("empolyeedepartment");
                });

            modelBuilder.Entity("C43_G03_Ef03.models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("C43_G03_Ef03.models.Employee", b =>
                {
                    b.Navigation("ManageDept");
                });
#pragma warning restore 612, 618
        }
    }
}
